# Site settings
title: Hari Mohanraj
email: hari.mohanraj89@gmail.com
description: "Personal website of Hari Mohanraj"
baseurl: ""
url: "http://harimohanraj89.github.io"
twitter_username: hari_mohanraj
github_username:  harimohanraj89

# Build settings
markdown: kramdown
permalink: none
